name: Go
on: [push]
jobs:
  build:
    name: Build, Test and Lint
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -cover -race ./...
    - name: Lint
      run: make lint
