name: Go
on: [push]
jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: env
      run: env
    - name: go env
      run: go env
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Lint
      run: make lint
    - name: Build
      run: go build -v .
